const button = document.getElementById('button');
const funfact = document.getElementById('funfact');

funfact.style.display = 'none';

button.addEventListener('click', function() {
   
   if (funfact.style.display === 'none'){
       funfact.style.display = 'block';
       button.textContent = 'Hide Fun Fact';
   } else {
       funfact.style.display = 'none';
       button.textContent = 'Fun Fact Button';
   }
});
/*Some of this generated by DeepSeek and/or I used DeepSeek as help/a base for some of this
